.TH "org/izdevs/acidium/game Directory Reference" 3 "Version Alpha-0.1" "Acidium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org/izdevs/acidium/game Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBcrafting\fP"
.br
.ti -1c
.RI "directory \fBequipment\fP"
.br
.ti -1c
.RI "directory \fBinventory\fP"
.br
.in -1c
