.TH "org/izdevs/acidium/game/crafting Directory Reference" 3 "Version Alpha-0.1" "Acidium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org/izdevs/acidium/game/crafting Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCraftingRecipe\&.java\fP"
.br
.ti -1c
.RI "file \fBCraftingRecipeHolder\&.java\fP"
.br
.ti -1c
.RI "file \fBCraftingSlot\&.java\fP"
.br
.in -1c
