.TH "org/izdevs/acidium/tick Directory Reference" 3 "Version Alpha-0.1" "Acidium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org/izdevs/acidium/tick Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBTicked\&.java\fP"
.br
.ti -1c
.RI "file \fBTickManager\&.java\fP"
.br
.in -1c
