.TH "org.izdevs.acidium.basic.IDGenerator" 3 "Version Alpha-0.1" "Acidium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.izdevs.acidium.basic.IDGenerator
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static synchronized int \fBcreateId\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static synchronized int org\&.izdevs\&.acidium\&.basic\&.IDGenerator\&.createId ()\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acidium from the source code\&.
