.TH "org.izdevs.acidium.command.BasicCommands" 3 "Version Alpha-0.1" "Acidium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.izdevs.acidium.command.BasicCommands
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "String \fBversion\fP ()"
.br
.ti -1c
.RI "String \fBcredits\fP ()"
.br
.ti -1c
.RI "String \fBtestSqlConnection\fP ()"
.br
.ti -1c
.RI "String \fBregClassPathYaml\fP (@ShellOption(defaultValue='name') String name)"
.br
.ti -1c
.RI "String \fBnotes\fP (@ShellOption(defaultValue='ALL') String noteName)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "String org\&.izdevs\&.acidium\&.command\&.BasicCommands\&.credits ()"

.SS "String org\&.izdevs\&.acidium\&.command\&.BasicCommands\&.notes (@ShellOption(defaultValue='ALL') String noteName)"

.SS "String org\&.izdevs\&.acidium\&.command\&.BasicCommands\&.regClassPathYaml (@ShellOption(defaultValue='name') String name)"

.SS "String org\&.izdevs\&.acidium\&.command\&.BasicCommands\&.testSqlConnection ()"

.SS "String org\&.izdevs\&.acidium\&.command\&.BasicCommands\&.version ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acidium from the source code\&.
