.TH "org.izdevs.acidium.tick.TickManager" 3 "Version Alpha-0.1" "Acidium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.izdevs.acidium.tick.TickManager
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBupdateTPS\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBstepTick\fP ()"
.br
.ti -1c
.RI "static void \fBinit\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static int \fBtps\fP"
.br
.ti -1c
.RI "static long \fBold_tick\fP"
.br
.ti -1c
.RI "static long \fBtick\fP = 0"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static void org\&.izdevs\&.acidium\&.tick\&.TickManager\&.init ()\fR [static]\fP"

.SS "static void org\&.izdevs\&.acidium\&.tick\&.TickManager\&.stepTick ()\fR [static]\fP"

.SS "void org\&.izdevs\&.acidium\&.tick\&.TickManager\&.updateTPS ()"

.SH "Member Data Documentation"
.PP 
.SS "long org\&.izdevs\&.acidium\&.tick\&.TickManager\&.old_tick\fR [static]\fP"

.SS "long org\&.izdevs\&.acidium\&.tick\&.TickManager\&.tick = 0\fR [static]\fP"

.SS "int org\&.izdevs\&.acidium\&.tick\&.TickManager\&.tps\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acidium from the source code\&.
