.TH "org.izdevs.acidium.scheduling.ScheduledTask" 3 "Version Alpha-0.1" "Acidium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.izdevs.acidium.scheduling.ScheduledTask
.SH SYNOPSIS
.br
.PP
.PP
Inherits Runnable\&.
.PP
Inherited by \fBorg\&.izdevs\&.acidium\&.scheduling\&.DelayedTask\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "enum \fBState\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBrun\fP ()"
.br
.ti -1c
.RI "\fBScheduledTask\fP (Runnable task)"
.br
.ti -1c
.RI "void \fBexec\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.izdevs\&.acidium\&.scheduling\&.ScheduledTask\&.ScheduledTask (Runnable task)"

.SH "Member Function Documentation"
.PP 
.SS "void org\&.izdevs\&.acidium\&.scheduling\&.ScheduledTask\&.exec ()"
Executes the run 
.SS "void org\&.izdevs\&.acidium\&.scheduling\&.ScheduledTask\&.run ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acidium from the source code\&.
