.TH "org.izdevs.acidium.api.v1.v1.defined" 3 "Version Alpha-0.1" "Acidium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.izdevs.acidium.api.v1.v1.defined
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBUSER\fP"
.br
.ti -1c
.RI "\fBPLAYER\fP"
.br
.ti -1c
.RI "\fBMOB\fP"
.br
.ti -1c
.RI "\fBENTITY\fP"
.br
.ti -1c
.RI "\fBDEFAULT_SPAWNER\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "org\&.izdevs\&.acidium\&.api\&.v1\&.v1\&.defined\&.DEFAULT_SPAWNER"

.SS "org\&.izdevs\&.acidium\&.api\&.v1\&.v1\&.defined\&.ENTITY"

.SS "org\&.izdevs\&.acidium\&.api\&.v1\&.v1\&.defined\&.MOB"

.SS "org\&.izdevs\&.acidium\&.api\&.v1\&.v1\&.defined\&.PLAYER"

.SS "org\&.izdevs\&.acidium\&.api\&.v1\&.v1\&.defined\&.USER"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acidium from the source code\&.
