.TH "org.izdevs.acidium.world.TickedWorld" 3 "Version Alpha-0.1" "Acidium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.izdevs.acidium.world.TickedWorld
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBorg\&.izdevs\&.acidium\&.world\&.World\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTickedWorld\fP (Map< Point, \fBBlock\fP > map)"
.br
.ti -1c
.RI "void \fBaddPlayer\fP (\fBPlayer\fP player)"
.br
.ti -1c
.RI "void \fBaddMob\fP (\fBMob\fP mob)"
.br
.ti -1c
.RI "void \fBdelPlayer\fP (\fBPlayer\fP player)"
.br
.ti -1c
.RI "void \fBdelMob\fP (\fBMob\fP mob)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "volatile ArrayList< \fBMob\fP > \fBmobs\fP = new ArrayList<>()"
.br
.ti -1c
.RI "volatile ArrayList< \fBPlayer\fP > \fBplayers\fP = new ArrayList<\fBPlayer\fP>()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.izdevs\&.acidium\&.world\&.TickedWorld\&.TickedWorld (Map< Point, \fBBlock\fP > map)"

.SH "Member Function Documentation"
.PP 
.SS "void org\&.izdevs\&.acidium\&.world\&.TickedWorld\&.addMob (\fBMob\fP mob)"

.SS "void org\&.izdevs\&.acidium\&.world\&.TickedWorld\&.addPlayer (\fBPlayer\fP player)"

.SS "void org\&.izdevs\&.acidium\&.world\&.TickedWorld\&.delMob (\fBMob\fP mob)"

.SS "void org\&.izdevs\&.acidium\&.world\&.TickedWorld\&.delPlayer (\fBPlayer\fP player)"

.SH "Member Data Documentation"
.PP 
.SS "volatile ArrayList<\fBMob\fP> org\&.izdevs\&.acidium\&.world\&.TickedWorld\&.mobs = new ArrayList<>()"

.SS "volatile ArrayList<\fBPlayer\fP> org\&.izdevs\&.acidium\&.world\&.TickedWorld\&.players = new ArrayList<\fBPlayer\fP>()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acidium from the source code\&.
