.TH "org.izdevs.acidium.security" 3 "Version Alpha-0.1" "Acidium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.izdevs.acidium.security
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAuthorizationContent\fP"
.br
.ti -1c
.RI "class \fBPlayerManager\fP"
.br
.ti -1c
.RI "interface \fBRoleController\fP"
.br
.ti -1c
.RI "class \fBRoleManager\fP"
.br
.ti -1c
.RI "class \fBSessionDetail\fP"
.br
.ti -1c
.RI "class \fBSessionGenerator\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Acidium from the source code\&.
