.TH "org.izdevs.acidium.utils.NumberUtils" 3 "Version Alpha-0.1" "Acidium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.izdevs.acidium.utils.NumberUtils
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static boolean \fBisInRange\fP (int starting, int bound, int a)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static boolean org\&.izdevs\&.acidium\&.utils\&.NumberUtils\&.isInRange (int starting, int bound, int a)\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acidium from the source code\&.
