.TH "org.izdevs.acidium.game.crafting.CraftingSlot" 3 "Version Alpha-0.1" "Acidium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.izdevs.acidium.game.crafting.CraftingSlot
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCraftingSlot\fP (int x, int y, \fBEquipment\fP equipment)"
.br
.ti -1c
.RI "\fBCraftingSlot\fP (\fBEquipment\fP equipment)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.izdevs\&.acidium\&.game\&.crafting\&.CraftingSlot\&.CraftingSlot (int x, int y, \fBEquipment\fP equipment)"

.SS "org\&.izdevs\&.acidium\&.game\&.crafting\&.CraftingSlot\&.CraftingSlot (\fBEquipment\fP equipment)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acidium from the source code\&.
