.TH "org.izdevs.acidium.utils.SpringBeanUtils" 3 "Version Alpha-0.1" "Acidium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.izdevs.acidium.utils.SpringBeanUtils
.SH SYNOPSIS
.br
.PP
.PP
Inherits ApplicationContextAware\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetApplicationContext\fP (ApplicationContext applicationContext)  throws BeansException "
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Object \fBgetBean\fP (String name)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static Object org\&.izdevs\&.acidium\&.utils\&.SpringBeanUtils\&.getBean (String name)\fR [static]\fP"

.SS "void org\&.izdevs\&.acidium\&.utils\&.SpringBeanUtils\&.setApplicationContext (ApplicationContext applicationContext) throws BeansException"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acidium from the source code\&.
