.TH "org.izdevs.acidium.serialization.NBTParser" 3 "Version Alpha-0.1" "Acidium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.izdevs.acidium.serialization.NBTParser
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBregisterNBTDef\fP (InputStream raw)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static ArrayList< \fBCommandDefinition\fP > \fBdefinitions\fP = new ArrayList<>()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static void org\&.izdevs\&.acidium\&.serialization\&.NBTParser\&.registerNBTDef (InputStream raw)\fR [static]\fP"

.SH "Member Data Documentation"
.PP 
.SS "ArrayList<\fBCommandDefinition\fP> org\&.izdevs\&.acidium\&.serialization\&.NBTParser\&.definitions = new ArrayList<>()\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acidium from the source code\&.
