.TH "org.izdevs.acidium.security.RoleController" 3 "Version Alpha-0.1" "Acidium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.izdevs.acidium.security.RoleController
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBorg\&.izdevs\&.acidium\&.networking\&.ServerHandlerRoleController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "boolean \fBcheckIfGranted\fP (\fBRole\fP role)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "boolean org\&.izdevs\&.acidium\&.security\&.RoleController\&.checkIfGranted (\fBRole\fP role)"

.PP
Implemented in \fBorg\&.izdevs\&.acidium\&.networking\&.ServerHandlerRoleController\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Acidium from the source code\&.
