.TH "org.izdevs.acidium.networking.ServerHandlerRoleController" 3 "Version Alpha-0.1" "Acidium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.izdevs.acidium.networking.ServerHandlerRoleController
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.izdevs\&.acidium\&.security\&.RoleController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "boolean \fBcheckIfGranted\fP (\fBRole\fP role)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "boolean org\&.izdevs\&.acidium\&.networking\&.ServerHandlerRoleController\&.checkIfGranted (\fBRole\fP role)"

.PP
Implements \fBorg\&.izdevs\&.acidium\&.security\&.RoleController\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Acidium from the source code\&.
