.TH "org.izdevs.acidium.configuration.Config" 3 "Version Alpha-0.1" "Acidium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.izdevs.acidium.configuration.Config
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "boolean \fBgenerateWorldUponStart\fP ()"
.br
.ti -1c
.RI "DataSource \fBgetDataSource\fP ()"
.br
.ti -1c
.RI "SecurityFilterChain \fBfilterChain\fP (HttpSecurity http)  throws Exception "
.br
.ti -1c
.RI "LettuceConnectionFactory \fBconnectionFactory\fP ()"
.br
.ti -1c
.RI "HttpSessionIdResolver \fBhttpSessionIdResolver\fP ()"
.br
.ti -1c
.RI "int \fBgetTicksPerSecond\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBgetMaxPlayers\fP ()"
.br
.ti -1c
.RI "static String \fBversion\fP ()"
.br
.ti -1c
.RI "static String \fBgetCredits\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final int \fBticksPerSecond\fP = 20"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "LettuceConnectionFactory org\&.izdevs\&.acidium\&.configuration\&.Config\&.connectionFactory ()"

.SS "SecurityFilterChain org\&.izdevs\&.acidium\&.configuration\&.Config\&.filterChain (HttpSecurity http) throws Exception"

.SS "boolean org\&.izdevs\&.acidium\&.configuration\&.Config\&.generateWorldUponStart ()"

.SS "static String org\&.izdevs\&.acidium\&.configuration\&.Config\&.getCredits ()\fR [static]\fP"

.SS "DataSource org\&.izdevs\&.acidium\&.configuration\&.Config\&.getDataSource ()"

.SS "static int org\&.izdevs\&.acidium\&.configuration\&.Config\&.getMaxPlayers ()\fR [static]\fP"

.SS "int org\&.izdevs\&.acidium\&.configuration\&.Config\&.getTicksPerSecond ()"

.SS "HttpSessionIdResolver org\&.izdevs\&.acidium\&.configuration\&.Config\&.httpSessionIdResolver ()"

.SS "static String org\&.izdevs\&.acidium\&.configuration\&.Config\&.version ()\fR [static]\fP"

.SH "Member Data Documentation"
.PP 
.SS "final int org\&.izdevs\&.acidium\&.configuration\&.Config\&.ticksPerSecond = 20\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acidium from the source code\&.
