.TH "org.izdevs.acidium.security.RoleManager" 3 "Version Alpha-0.1" "Acidium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.izdevs.acidium.security.RoleManager
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBregisterRole\fP (\fBRole\fP role)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static volatile Set< \fBRole\fP > \fBroles\fP = new HashSet<>()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static void org\&.izdevs\&.acidium\&.security\&.RoleManager\&.registerRole (\fBRole\fP role)\fR [static]\fP"

.SH "Member Data Documentation"
.PP 
.SS "volatile Set<\fBRole\fP> org\&.izdevs\&.acidium\&.security\&.RoleManager\&.roles = new HashSet<>()\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acidium from the source code\&.
