.TH "org.izdevs.acidium.tick.Ticked" 3 "Version Alpha-0.1" "Acidium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.izdevs.acidium.tick.Ticked
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBorg\&.izdevs\&.acidium\&.entity\&.AbstractMobSpawner\fP, \fBorg\&.izdevs\&.acidium\&.entity\&.MobHolder\fP, and \fBorg\&.izdevs\&.acidium\&.serialization\&.Resource\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBtick\fP ()"
.br
.ti -1c
.RI "default void \fBstopTick\fP ()"
.br
.ti -1c
.RI "default void \fBpause\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "default void org\&.izdevs\&.acidium\&.tick\&.Ticked\&.pause ()"

.SS "default void org\&.izdevs\&.acidium\&.tick\&.Ticked\&.stopTick ()"

.SS "void org\&.izdevs\&.acidium\&.tick\&.Ticked\&.tick ()"

.PP
Implemented in \fBorg\&.izdevs\&.acidium\&.api\&.v1\&.DefaultSpawner\fP, \fBorg\&.izdevs\&.acidium\&.entity\&.AbstractMobSpawner\fP, \fBorg\&.izdevs\&.acidium\&.entity\&.MobHolder\fP, and \fBorg\&.izdevs\&.acidium\&.serialization\&.Resource\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Acidium from the source code\&.
