.TH "org.izdevs.acidium.basic.DefaultBehaviourController" 3 "Version Alpha-0.1" "Acidium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.izdevs.acidium.basic.DefaultBehaviourController
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.izdevs\&.acidium\&.basic\&.AbstractBehaviourController\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "FloatArray \fBnextStep\fP ()"
.br
.ti -1c
.RI "\fBDefaultBehaviourController\fP (\fBWorld\fP world)"
.br
.ti -1c
.RI "void \fBmove\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.izdevs\&.acidium\&.basic\&.DefaultBehaviourController\&.DefaultBehaviourController (\fBWorld\fP world)"

.SH "Member Function Documentation"
.PP 
.SS "void org\&.izdevs\&.acidium\&.basic\&.DefaultBehaviourController\&.move ()"

.SS "FloatArray org\&.izdevs\&.acidium\&.basic\&.DefaultBehaviourController\&.nextStep ()"

.PP
Reimplemented from \fBorg\&.izdevs\&.acidium\&.basic\&.AbstractBehaviourController\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Acidium from the source code\&.
