.TH "org.izdevs.acidium.basic.UserRepository" 3 "Version Alpha-0.1" "Acidium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.izdevs.acidium.basic.UserRepository
.SH SYNOPSIS
.br
.PP
.PP
Inherits Repository< User, Integer >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUser\fP \fBfindById\fP (Long id)"
.br
.ti -1c
.RI "\fBUser\fP \fBfindUserByRole\fP (\fBRole\fP role)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBUser\fP org\&.izdevs\&.acidium\&.basic\&.UserRepository\&.findById (Long id)"

.SS "\fBUser\fP org\&.izdevs\&.acidium\&.basic\&.UserRepository\&.findUserByRole (\fBRole\fP role)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acidium from the source code\&.
