.TH "org.izdevs.acidium.StartupTasksRunner" 3 "Version Alpha-0.1" "Acidium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.izdevs.acidium.StartupTasksRunner
.SH SYNOPSIS
.br
.PP
.PP
Inherits ApplicationRunner\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBrun\fP (ApplicationArguments args)  throws Exception "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "boolean \fBgenerateWorld\fP"
.br
.ti -1c
.RI "int \fBmaxPlayers\fP"
.br
.ti -1c
.RI "DataSource \fBdataSource\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static MessageDispatcher \fBdispatcher\fP = null"
.br
.ti -1c
.RI "static Connection \fBSQLConnection\fP = null"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void org\&.izdevs\&.acidium\&.StartupTasksRunner\&.run (ApplicationArguments args) throws Exception"

.SH "Member Data Documentation"
.PP 
.SS "DataSource org\&.izdevs\&.acidium\&.StartupTasksRunner\&.dataSource"

.SS "MessageDispatcher org\&.izdevs\&.acidium\&.StartupTasksRunner\&.dispatcher = null\fR [static]\fP"

.SS "boolean org\&.izdevs\&.acidium\&.StartupTasksRunner\&.generateWorld"

.SS "int org\&.izdevs\&.acidium\&.StartupTasksRunner\&.maxPlayers"

.SS "Connection org\&.izdevs\&.acidium\&.StartupTasksRunner\&.SQLConnection = null\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acidium from the source code\&.
