.TH "org.izdevs.acidium.security.PlayerManager" 3 "Version Alpha-0.1" "Acidium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.izdevs.acidium.security.PlayerManager
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBadd\fP (\fBPlayer\fP player)"
.br
.ti -1c
.RI "static void \fBremove\fP (\fBPlayer\fP player)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static Set< \fBPlayer\fP > \fBplayers\fP = new HashSet<>()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static void org\&.izdevs\&.acidium\&.security\&.PlayerManager\&.add (\fBPlayer\fP player)\fR [static]\fP"

.SS "static void org\&.izdevs\&.acidium\&.security\&.PlayerManager\&.remove (\fBPlayer\fP player)\fR [static]\fP"

.SH "Member Data Documentation"
.PP 
.SS "Set<\fBPlayer\fP> org\&.izdevs\&.acidium\&.security\&.PlayerManager\&.players = new HashSet<>()\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acidium from the source code\&.
