.TH "org.izdevs.acidium.game.crafting.CraftingRecipeHolder" 3 "Version Alpha-0.1" "Acidium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.izdevs.acidium.game.crafting.CraftingRecipeHolder
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBregisterRecipe\fP (\fBCraftingRecipe\fP recipe)"
.br
.ti -1c
.RI "static void \fBinit\fP ()  throws InstantiationException, IllegalAccessException "
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static void org\&.izdevs\&.acidium\&.game\&.crafting\&.CraftingRecipeHolder\&.init () throws InstantiationException, IllegalAccessException\fR [static]\fP"

.SS "static void org\&.izdevs\&.acidium\&.game\&.crafting\&.CraftingRecipeHolder\&.registerRecipe (\fBCraftingRecipe\fP recipe)\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acidium from the source code\&.
