.TH "org.izdevs.acidium.world.StructureHolder" 3 "Version Alpha-0.1" "Acidium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.izdevs.acidium.world.StructureHolder
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBregister\fP (\fBStructure\fP structure)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static volatile ArrayList< \fBStructure\fP > \fBstructures\fP = new ArrayList<>()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static void org\&.izdevs\&.acidium\&.world\&.StructureHolder\&.register (\fBStructure\fP structure)\fR [static]\fP"

.SH "Member Data Documentation"
.PP 
.SS "volatile ArrayList<\fBStructure\fP> org\&.izdevs\&.acidium\&.world\&.StructureHolder\&.structures = new ArrayList<>()\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acidium from the source code\&.
