.TH "org.izdevs.acidium.world.DefaultWorldGenerator" 3 "Version Alpha-0.1" "Acidium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.izdevs.acidium.world.DefaultWorldGenerator
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.izdevs\&.acidium\&.world\&.WorldGenerator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWorld\fP \fBgenerate\fP (long \fBseed\fP)"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBorg\&.izdevs\&.acidium\&.world\&.WorldGenerator\fP
.in +1c
.ti -1c
.RI "String \fBseed\fP = ''"
.br
.ti -1c
.RI "String \fBtype\fP = ''"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBWorld\fP org\&.izdevs\&.acidium\&.world\&.DefaultWorldGenerator\&.generate (long seed)"

.PP
Implements \fBorg\&.izdevs\&.acidium\&.world\&.WorldGenerator\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Acidium from the source code\&.
