.TH "org.izdevs.acidium.serialization.SpecObject" 3 "Version Alpha-0.1" "Acidium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.izdevs.acidium.serialization.SpecObject
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSpecObject\fP (String key, Object value)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.izdevs\&.acidium\&.serialization\&.SpecObject\&.SpecObject (String key, Object value)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acidium from the source code\&.
