.TH "org.izdevs.acidium.world.BlockType" 3 "Version Alpha-0.1" "Acidium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.izdevs.acidium.world.BlockType
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBVOID\fP"
.br
.ti -1c
.RI "\fBCREDIT_BLOCK\fP"
.br
.ti -1c
.RI "\fBWOOD\fP"
.br
.ti -1c
.RI "\fBSTONE\fP"
.br
.ti -1c
.RI "\fBSPAWNER\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "org\&.izdevs\&.acidium\&.world\&.BlockType\&.CREDIT_BLOCK"

.SS "org\&.izdevs\&.acidium\&.world\&.BlockType\&.SPAWNER"

.SS "org\&.izdevs\&.acidium\&.world\&.BlockType\&.STONE"

.SS "org\&.izdevs\&.acidium\&.world\&.BlockType\&.VOID"

.SS "org\&.izdevs\&.acidium\&.world\&.BlockType\&.WOOD"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acidium from the source code\&.
