.TH "org.izdevs.acidium.world.BlockDataHolder" 3 "Version Alpha-0.1" "Acidium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.izdevs.acidium.world.BlockDataHolder
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBregisterSpec\fP (\fBBlockSpec\fP spec)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static ArrayList< \fBBlockSpec\fP > \fBregistered\fP = new ArrayList<>()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static void org\&.izdevs\&.acidium\&.world\&.BlockDataHolder\&.registerSpec (\fBBlockSpec\fP spec)\fR [static]\fP"

.SH "Member Data Documentation"
.PP 
.SS "ArrayList<\fBBlockSpec\fP> org\&.izdevs\&.acidium\&.world\&.BlockDataHolder\&.registered = new ArrayList<>()\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acidium from the source code\&.
