.TH "org.izdevs.acidium.serialization.ResourceFacade" 3 "Version Alpha-0.1" "Acidium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.izdevs.acidium.serialization.ResourceFacade
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBResource\fP \fBfindByNameAndApiIs\fP (String name, boolean api)"
.br
.ti -1c
.RI "\fBResource\fP \fBfindByNameAndAssociatedApi\fP (String name, \fBAPI\fP api)"
.br
.ti -1c
.RI "\fBResource\fP \fBfindResource\fP (String name, String api)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBregisterAPI\fP (\fBAPI\fP api)"
.br
.ti -1c
.RI "static void \fBregisterResource\fP (\fBResource\fP resource)"
.br
.ti -1c
.RI "static void \fBstart\fP ()  throws InstantiationException, IllegalAccessException "
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBResource\fP org\&.izdevs\&.acidium\&.serialization\&.ResourceFacade\&.findByNameAndApiIs (String name, boolean api)"

.SS "\fBResource\fP org\&.izdevs\&.acidium\&.serialization\&.ResourceFacade\&.findByNameAndAssociatedApi (String name, \fBAPI\fP api)"

.SS "\fBResource\fP org\&.izdevs\&.acidium\&.serialization\&.ResourceFacade\&.findResource (String name, String api)"

.SS "static void org\&.izdevs\&.acidium\&.serialization\&.ResourceFacade\&.registerAPI (\fBAPI\fP api)\fR [static]\fP"

.SS "static void org\&.izdevs\&.acidium\&.serialization\&.ResourceFacade\&.registerResource (\fBResource\fP resource)\fR [static]\fP"

.SS "static void org\&.izdevs\&.acidium\&.serialization\&.ResourceFacade\&.start () throws InstantiationException, IllegalAccessException\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acidium from the source code\&.
