.TH "org.izdevs.acidium.Metrics" 3 "Version Alpha-0.1" "Acidium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.izdevs.acidium.Metrics
.SH SYNOPSIS
.br
.PP
.PP
Inherits MeterBinder\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBbindTo\fP (@NonNull MeterRegistry meterRegistry)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBgetEntityCount\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static Counter \fBrequests\fP"
.br
.ti -1c
.RI "static Gauge \fBplayers\fP"
.br
.ti -1c
.RI "static Counter \fBticksElapsed\fP"
.br
.ti -1c
.RI "static Gauge \fBticksPerSecond\fP"
.br
.ti -1c
.RI "static Counter \fBapiRequests\fP"
.br
.ti -1c
.RI "static Gauge \fBentities\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void org\&.izdevs\&.acidium\&.Metrics\&.bindTo (@NonNull MeterRegistry meterRegistry)"

.SS "static int org\&.izdevs\&.acidium\&.Metrics\&.getEntityCount ()\fR [static]\fP"

.SH "Member Data Documentation"
.PP 
.SS "Counter org\&.izdevs\&.acidium\&.Metrics\&.apiRequests\fR [static]\fP"

.SS "Gauge org\&.izdevs\&.acidium\&.Metrics\&.entities\fR [static]\fP"

.SS "Gauge org\&.izdevs\&.acidium\&.Metrics\&.players\fR [static]\fP"

.SS "Counter org\&.izdevs\&.acidium\&.Metrics\&.requests\fR [static]\fP"

.SS "Counter org\&.izdevs\&.acidium\&.Metrics\&.ticksElapsed\fR [static]\fP"

.SS "Gauge org\&.izdevs\&.acidium\&.Metrics\&.ticksPerSecond\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acidium from the source code\&.
