.TH "org.izdevs.acidium.scheduling.LoopManager" 3 "Version Alpha-0.1" "Acidium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.izdevs.acidium.scheduling.LoopManager
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBregisterTask\fP (\fBScheduledTask\fP task)"
.br
.ti -1c
.RI "static void \fBscheduleAsyncDelayedTask\fP (\fBDelayedTask\fP task)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static void org\&.izdevs\&.acidium\&.scheduling\&.LoopManager\&.registerTask (\fBScheduledTask\fP task)\fR [static]\fP"

.SS "static void org\&.izdevs\&.acidium\&.scheduling\&.LoopManager\&.scheduleAsyncDelayedTask (\fBDelayedTask\fP task)\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acidium from the source code\&.
