.TH "org.izdevs.acidium.api.v1.Role.Level" 3 "Version Alpha-0.1" "Acidium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.izdevs.acidium.api.v1.Role.Level
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLevel\fP (int \fBid\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBADMIN\fP =(0)"
.br
.ti -1c
.RI "\fBMODERATOR\fP =(1)"
.br
.ti -1c
.RI "\fBPLAYER\fP =(2)"
.br
.ti -1c
.RI "final int \fBid\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.izdevs\&.acidium\&.api\&.v1\&.Role\&.Level\&.Level (int id)"

.SH "Member Data Documentation"
.PP 
.SS "org\&.izdevs\&.acidium\&.api\&.v1\&.Role\&.Level\&.ADMIN =(0)"

.SS "final int org\&.izdevs\&.acidium\&.api\&.v1\&.Role\&.Level\&.id"

.SS "org\&.izdevs\&.acidium\&.api\&.v1\&.Role\&.Level\&.MODERATOR =(1)"

.SS "org\&.izdevs\&.acidium\&.api\&.v1\&.Role\&.Level\&.PLAYER =(2)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acidium from the source code\&.
