.TH "org.izdevs.acidium.api.v1.Role" 3 "Version Alpha-0.1" "Acidium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.izdevs.acidium.api.v1.Role
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "enum \fBLevel\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRole\fP (String name)"
.br
.ti -1c
.RI "\fBRole\fP (String name, Set< \fBLevel\fP > levels)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "org\&.izdevs\&.acidium\&.api\&.v1\&.Role\&.Role (String name)"

.SS "org\&.izdevs\&.acidium\&.api\&.v1\&.Role\&.Role (String name, Set< \fBLevel\fP > levels)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acidium from the source code\&.
