.TH "org.izdevs.acidium.entity.AbstractMobSpawner" 3 "Version Alpha-0.1" "Acidium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.izdevs.acidium.entity.AbstractMobSpawner
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBorg\&.izdevs\&.acidium\&.tick\&.Ticked\fP\&.
.PP
Inherited by \fBorg\&.izdevs\&.acidium\&.api\&.v1\&.DefaultSpawner\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBspawn\fP ()"
.br
.ti -1c
.RI "void \fBtick\fP ()"
.br
.ti -1c
.RI "default void \fBaddJob\fP (\fBMob\fP mob)"
.br
.ti -1c
.RI "default void \fBdeleteJob\fP (\fBMob\fP mob)"
.br
.ti -1c
.RI "void \fBspawnManual\fP (\fBMob\fP mob)"
.br
.in -1c

Public Member Functions inherited from \fBorg\&.izdevs\&.acidium\&.tick\&.Ticked\fP
.in +1c
.ti -1c
.RI "default void \fBstopTick\fP ()"
.br
.ti -1c
.RI "default void \fBpause\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< \fBMob\fP > \fBjobQueue\fP = new ArrayList<>()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "default void org\&.izdevs\&.acidium\&.entity\&.AbstractMobSpawner\&.addJob (\fBMob\fP mob)"

.SS "default void org\&.izdevs\&.acidium\&.entity\&.AbstractMobSpawner\&.deleteJob (\fBMob\fP mob)"

.SS "void org\&.izdevs\&.acidium\&.entity\&.AbstractMobSpawner\&.spawn ()"

.PP
Implemented in \fBorg\&.izdevs\&.acidium\&.api\&.v1\&.DefaultSpawner\fP\&.
.SS "void org\&.izdevs\&.acidium\&.entity\&.AbstractMobSpawner\&.spawnManual (\fBMob\fP mob)"

.PP
Implemented in \fBorg\&.izdevs\&.acidium\&.api\&.v1\&.DefaultSpawner\fP\&.
.SS "void org\&.izdevs\&.acidium\&.entity\&.AbstractMobSpawner\&.tick ()"

.PP
Implements \fBorg\&.izdevs\&.acidium\&.tick\&.Ticked\fP\&.
.PP
Implemented in \fBorg\&.izdevs\&.acidium\&.api\&.v1\&.DefaultSpawner\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "List<\fBMob\fP> org\&.izdevs\&.acidium\&.entity\&.AbstractMobSpawner\&.jobQueue = new ArrayList<>()"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acidium from the source code\&.
