.TH "org.izdevs.acidium.AcidiumApplication" 3 "Version Alpha-0.1" "Acidium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.izdevs.acidium.AcidiumApplication
.SH SYNOPSIS
.br
.PP
.PP
Inherits SpringApplication\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBdistance\fP (double x1, double y1, double x2, double y2)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.ti -1c
.RI "static void \fBloadNBT\fP ()  throws IOException "
.br
.ti -1c
.RI "static int \fBgetFreePort\fP ()"
.br
.ti -1c
.RI "static String \fBbcrypt\fP (String string)"
.br
.ti -1c
.RI "static void \fBreadAndPrintNote\fP ()  throws IOException "
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static String org\&.izdevs\&.acidium\&.AcidiumApplication\&.bcrypt (String string)\fR [static]\fP"

.SS "double org\&.izdevs\&.acidium\&.AcidiumApplication\&.distance (double x1, double y1, double x2, double y2)"

.SS "static int org\&.izdevs\&.acidium\&.AcidiumApplication\&.getFreePort ()\fR [static]\fP"

.SS "static void org\&.izdevs\&.acidium\&.AcidiumApplication\&.loadNBT () throws IOException\fR [static]\fP"

.SS "static void org\&.izdevs\&.acidium\&.AcidiumApplication\&.main (String[] args)\fR [static]\fP"

.SS "static void org\&.izdevs\&.acidium\&.AcidiumApplication\&.readAndPrintNote () throws IOException\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acidium from the source code\&.
