.TH "org.izdevs.acidium.game.equipment.EquipmentHolder" 3 "Version Alpha-0.1" "Acidium" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.izdevs.acidium.game.equipment.EquipmentHolder
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBregister\fP (\fBEquipment\fP equipment)"
.br
.ti -1c
.RI "static void \fBinit\fP ()  throws InstantiationException, IllegalAccessException "
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static void org\&.izdevs\&.acidium\&.game\&.equipment\&.EquipmentHolder\&.init () throws InstantiationException, IllegalAccessException\fR [static]\fP"

.SS "static void org\&.izdevs\&.acidium\&.game\&.equipment\&.EquipmentHolder\&.register (\fBEquipment\fP equipment)\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Acidium from the source code\&.
